# A query to obtain all steps of a workflow and the relevant in- and outputs.

PREFIX ta: <https://github.com/quangis/transformation-algebra#>
PREFIX wf: <http://geographicknowledge.de/vocab/Workflow.rdf#>

SELECT
    ?step ?tool
    ?output ?is_final_output
    ?x1 ?x2 ?x3
WHERE {
    ?wf wf:edge ?step.
    ?step wf:applicationOf ?tool.

    # What are the inputs?
    OPTIONAL { ?step wf:input1 ?x1. }
    OPTIONAL { ?step wf:input2 ?x2. }
    OPTIONAL { ?step wf:input3 ?x3. }

    # Is this the final step?
    ?step wf:output ?output.
    OPTIONAL {
        { ?next_step wf:input1 ?output }
        UNION
        { ?next_step wf:input2 ?output }
        UNION
        { ?next_step wf:input3 ?output }.
    }
    BIND (!bound(?next_step) AS ?is_final_output).
