question: |
  Which urban areas are at risk from water depletion in Ogandala (High Plains)
  Aquifer, US?
workflows:
  - OgallalaAquifer
transform:
  - ObjectInfo(Nom)
  - all:
    - - R2(Obj, Reg)
      - ObjectInfo(Nom) # urban areas
    - - R2(Obj, Reg)
      - ObjectInfo(Nom) # aquifer
    - - R2(Loc, Nom)
      - R2(Nom, Reg) # precipitation coverage
    - - R2(Loc, Nom)
      - R2(Nom, Reg) # irrigation coverage
